# Generated by Django 5.2.7 on 2025-10-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_partial_patients',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('mobile_app', 'Mobile App')], max_length=50),
        ),
    ]
