# Generated by Django 5.2.7 on 2025-10-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenant_allow_partial_patients_alter_tenant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='patient_visible_fields',
            field=models.JSONField(default=list, help_text="List of Patient model fields this tenant is allowed to see, e.g. ['name', 'email'] or ['all']"),
        ),
    ]
