# Generated by Django 5.2.7 on 2025-10-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_tenant_patient_visible_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='patient_records_type',
            field=models.CharField(choices=[('rigid', 'Rigido'), ('flexible', 'Flexible')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
