# Generated by Django 5.2.7 on 2025-10-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_tenant_patient_records_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ssn_hippa_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
