# Generated by Django 5.2.7 on 2025-10-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_email_alter_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ssn_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
